### ISSUE TITLE
WCAG 2.0 level AA compliance

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#115]

**Comment by stroudn1** [comment]
Hello @p-galligan ! Are you looking for someone to report bugs/find accessibility issues with this (& possibly fix)? Interested in learning more about this issue. Thanks!

**Comment by helrond** [comment]
Hey @stroudn1 this is a placeholder issue right now. We'll be looking at this more closely in the future - thanks for your offering!

**Comment by HaSistrunk** [comment]
This is addressed in the frontend [dimes repo](https://github.com/RockefellerArchiveCenter/dimes), so I'm closing it here.
