### ISSUE TITLE
Determine/develop language expression mapping for transformers

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#130]
Right now, the json schema requires a language expression, but we are only pulling in the three-digit ISO language code. We would have to develop some way to map that against an enumerated list.

**Comment by helrond** [comment]
There are a number of Python languages that allow you to get a language name based on a language code. In Aurora we use [iso-639](https://pypi.org/project/iso-639/). The code for that is [here](https://github.com/RockefellerArchiveCenter/aurora/blob/master/aurora/bag_transfer/lib/bag_checker.py#L138), in this case we'd just want to return name of the language object after we fetched it.

**Comment by helrond** [comment]
Looking at the code, I actually believe this is already accounted for.

**Comment by p-galligan** [comment]
As mentioned, already accounted for, suggest closing.
