### ISSUE TITLE
Fix notes mapping

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#133]
Notes aren't being mapped or transformed correctly currently. Currently no data is displayed for notes.

Figure out how to fix the mapping or transformations.

**Comment by p-galligan** [comment]
Just caught this, but we don't have notes mapping working correctly for Agents.

**Comment by helrond** [comment]
Part of #140

**Comment by p-galligan** [comment]
Mostly fixed except for #140 .

Main commits are: https://github.com/RockefellerArchiveCenter/pisces/commit/d6a7ffeca33bc51d79e3c9d9d979716a8047ce33
https://github.com/RockefellerArchiveCenter/pisces/commit/2874f75b0d1009bba64f4633da55b88375555059
https://github.com/RockefellerArchiveCenter/pisces/commit/71cac67ef93ffe8f93d388c6d905476029ea3304
