### ISSUE TITLE
Notes aren't transforming for agents and terms

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#140]
Note logic isn't working for Agents and Term objects

**Comment by helrond** [comment]
@p-galligan I've fixed this for Agents by adding an additional note type the mapping (the subnotes mapping was looking for the `jsonmodel_type` of the parent note, which in agents is `note_bioghist`). 

Correct me if I'm wrong, but I don't believe that Subjects in ArchivesSpace have notes associated with them?
