### ISSUE TITLE
Parse archival_objects into Objects and Collections

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pisces#151]
Archival objects in ArchivesSpace can be either RAC Objects or Collections, depending on whether or not they have children. Add additional logic to parse Objects from Collections. The ArchivesSpace `tree/node` endpoint [looks promising](https://archivesspace.github.io/archivesspace/api/#fetch-tree-information-for-an-archival-object-record-within-a-tree)

**Comment by p-galligan** [comment]
So are you thinking that checking `child_count` could quickly tell us whether it's an object or a collection?

**Comment by helrond** [comment]
Yes, exactly.
