### ISSUE TITLE
Add inferred field flag for data that is inherited by closest_parent_value

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#167]
## Describe the bug
Currently, a collection requires an extent to validate. However, for archival objects that the model recognizes as collections, the extent may not be accurate. These objects are inheriting the next closest extent from an ancestor. This is not going to be accurate. Mappings are working as intended, but don't know how we want to have accurate extents represented. 

## Additional context
Not a huge impact except for display in DIMES.

Would like to get @helrond 's thoughts on a solution for this.

**Comment by helrond** [comment]
Good call - I think this is an issue for anything we're inheriting down, including dates and (maybe) creator. I want to think about this a bit more, but I'm wondering as a first step if we should add an "inferred" (or similar) flag on data elements which are not specified directly on objects?
