### ISSUE TITLE
Transformation failing on Library items - Extent Type

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/pisces#186]
## Describe the bug
Library objects include "Bound Volumes" as an extent type, but this is not an acceptable choice in our extents.

## To reproduce
1. Run transformations on an object with "Bound Volumes" as an extent type

**Comment by helrond** [comment]
Thoughts on how to solve this? Options that have occurred to me thus far:
- ignore resources that start with `LI`
- look for some other piece of data on the resource in order to ignore
