### ISSUE TITLE
Consider removing controlled values for extent types

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/pisces#315]
## Is your feature request related to a problem? Please describe.
Now that we are calculating extent from instances, a number of new types have been introduced such as `drawer`, `page`, etc.

## Describe the solution you'd like
- Consider removing controlled values
- Improve test coverage to account for these cases

## Describe alternatives you've considered
- Add additional terms (found in `Container Type` list in AS) to controlled values, both in Odin resources and schema.

**Comment by helrond** [comment]
@p-galligan can I get your thoughts on this?

**Comment by p-galligan** [comment]
@helrond Do you mean consider removing a list of controlled values from the code? If controlled value terms keep getting added to AS, I'm not sure it's sustainable to have a defined and set list of types that we'd have to update over time.

**Comment by helrond** [comment]
@p-galligan yes. Currently extent types are a controlled list. However, given that this list is now the combination of two controlled (but lengthy) lists in AS, I'm feeling like the usefulness of having controlled lists in Odin Resources and the RAC schema is somewhat reduced.
