### ISSUE TITLE
Issues with error handling for ingest/merge processes

### ISSUE THREAD

**Issue by kcloud** [RockefellerArchiveCenter/pisces#484]
## Describe the bug
For some records, we are unable to receive error reports from https://github.com/RockefellerArchiveCenter/pisces/blob/0fcdfd7a6055e6df58cc27058e31249cfe3ecca7/merger/mergers.py#L38. Previously, we were able to have actionable reporting.

It may be related to escape sequences introduced in recent updates or error coverage.

## To reproduce
Running local cron produces:
...
'total_hits'
'total_hits'
Error merging /repositories/10/archival_objects/488946: 'total_hits'
...
## Expected behavior
Previous error messages produced:
...
Error merging /repositories/10/archival_objects/490034: Object needs a properly formatted begin date
Object needs a properly formatted begin date (ex, ['1939-06-03']) : /resources/1294#tree::archival_object_490034
...

**Comment by helrond** [comment]
@kcloud just want to confirm this issue is resolved after pulling in recent updates.

**Comment by kcloud** [comment]
Yes, thanks, I'll close this issue.
