### ISSUE TITLE
Parsing error in indicator_to_integer helper

### ISSUE THREAD

**Issue by kcloud** [RockefellerArchiveCenter/pisces#506]
## Describe the bug
[Issue](https://github.com/RockefellerArchiveCenter/pisces/blob/0680f02953c677ccd67af4cd5c8a72425fbe2c68/merger/helpers.py#L11) appears in helper method that expects "An indicator can be an integer (23) a combination of integers and letters (23b) or just a letter (B)." Combinations of letters from [indicator-2 data](https://github.com/RockefellerArchiveCenter/pisces/blob/0680f02953c677ccd67af4cd5c8a72425fbe2c68/merger/mergers.py#L146), such as  "P-Re" will generate an error. 

## Expected behavior
Wrapping the ord() within a try/catch statement and accepting the first character will patch the errors and permit indexing at the expense of accurate reporting. Further implementations should consider the impact on data carefully.

**Comment by helrond** [comment]
Thanks @kcloud. Documenting here that the use case for this particular method is to add inferred extents to all objects. Some inaccuracies are expected.
