### ISSUE TITLE
Enable easy method for overriding rac-schemas dependency

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/pisces#523]
## Is your feature request related to a problem? Please describe.
There are likely to be divergent expectations on the practical use of ASpace data for the transformation validation described by [rac-schemas](https://github.com/RockefellerArchiveCenter/rac_schemas).  For example, to successfully index our records, we had to make the following changes, adding the `uniform_title` and removing the `creators` requirement:
https://github.com/ulsdevteam/rac_schemas/commit/c8a79c23ef63733b49fe9babb1dd5c50dc5d6ef2

Presuming that this kind of change is not suitable for an upstream PR, and presuming that others may have similar data mapping adjustments, it would be helpful to be able to override the `rac-schemas` dependency without publishing a new PyPi repo and editing the requirements and imports to reflect that repo rather than `rac-schemas`.

## Describe the solution you'd like
Allow for the rac-schemas in requirements.in to be replaced with a local dependency, as desired.

Our current strategy for this is:

- .gitignore a new folder rac_schemas
- sed requirements.in to replace "rac-schemas=.*" with "./rac_schemas"
- fork the rac-schemas repo, push new commits, and clone to "rac_schemas"
- build as usual

## Describe alternatives you've considered

- Should the changes be upstream PRs instead?  (indeterminate)
- Should we publish our own PyPi repo? (no, inelegant and awkward management)
- Should the rac-schemas always be a local python include, using git submodules to manage it (hmmm, maybe?)

## Additional context
Speculative commit as a proposed basis for a PR linked below.

**Comment by helrond** [comment]
Right now `rac_schemas` is both a bunch of JSONschema files as well as some helper code to validate objects. If we separate those two things and put the executable code (i.e. the code [here](https://github.com/RockefellerArchiveCenter/rac_schemas/blob/base/rac_schemas/__init__.py)) into a pip installable library, and maintain the static schema files separately, it simplifies what needs to be managed locally/per instance, which should really _just_ be the schemas themselves. Those can either be managed as a submodule or a pip install - there would be a config that would indicate where those files are stored locally so the validator can pick them up and do its thing. It's a bit more work but I think it's cleaner and easier to maintain over the long haul. Thoughts?
