### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [RockefellerArchiveCenter/pisces#9]
Hello @helrond 

I am a logo designer and I contribute to open source projects that do not have logo.  I have designed a minimalist logo consisting of multiple ideas that represent this project very well. I hope you like it. I'd like to hear your thoughts. Best regards...

![pisces](https://user-images.githubusercontent.com/36298335/56864125-6c6cf880-69c7-11e9-8a52-47c0a894de86.jpg)

Readme view;

![pisces2](https://user-images.githubusercontent.com/36298335/56864147-99211000-69c7-11e9-8c0c-03e359ccdfd3.png)

**Comment by helrond** [comment]
Thanks @reallinfo - we are not actively looking for branding for this project, as it is part of a larger organizational effort so will be branded with our organization's assets. Thank you for submitting this idea though, and if we have need for design work in the future I'll keep you in mind.
